# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bramble lab
email: cary@bramblelab.com
description: > # this means to ignore newlines until "baseurl:"
  Based out of the Baltimore Impact Hub, Bramble Lab is a social design initiative and design firm. Our passion lies in the belief that education is a fundamental human right, and that design is a powerful tool in securing that right. To that end, we work with organizations from across the city at the intersection of education, public health and policy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bramblelab.com" # the base hostname & protocol for your site
twitter_username: bramblelab
instagram_username: bramblelab

# Build settings
markdown: kramdown
